export const countries = [
    { id: 'AF+93', code: '+93', name: 'Afghanistan', flag: 'AF' },
    { id: 'AL+355', code: '+355', name: 'Albania', flag: 'AL' },
    { id: 'DZ+213', code: '+213', name: 'Algeria', flag: 'DZ' },
    { id: 'AD+376', code: '+376', name: 'Andorra', flag: 'AD' },
    { id: 'AO+244', code: '+244', name: 'Angola', flag: 'AO' },
    { id: 'AG+1268', code: '+1268', name: 'Antigua and Barbuda', flag: 'AG' },
    { id: 'AR+54', code: '+54', name: 'Argentina', flag: 'AR' },
    { id: 'AM+374', code: '+374', name: 'Armenia', flag: 'AM' },
    { id: 'AW+297', code: '+297', name: 'Aruba', flag: 'AW' },
    { id: 'AU+61', code: '+61', name: 'Australia', flag: 'AU' },
    { id: 'AT+43', code: '+43', name: 'Austria', flag: 'AT' },
    { id: 'AZ+994', code: '+994', name: 'Azerbaijan', flag: 'AZ' },
    { id: 'BS+1242', code: '+1242', name: 'Bahamas', flag: 'BS' },
    { id: 'BH+973', code: '+973', name: 'Bahrain', flag: 'BH' },
    { id: 'BD+880', code: '+880', name: 'Bangladesh', flag: 'BD' },
    { id: 'BB+1246', code: '+1246', name: 'Barbados', flag: 'BB' },
    { id: 'BY+375', code: '+375', name: 'Belarus', flag: 'BY' },
    { id: 'BE+32', code: '+32', name: 'Belgium', flag: 'BE' },
    { id: 'BZ+501', code: '+501', name: 'Belize', flag: 'BZ' },
    { id: 'BJ+229', code: '+229', name: 'Benin', flag: 'BJ' },
    { id: 'BT+975', code: '+975', name: 'Bhutan', flag: 'BT' },
    { id: 'BO+591', code: '+591', name: 'Bolivia', flag: 'BO' },
    { id: 'BA+387', code: '+387', name: 'Bosnia and Herzegovina', flag: 'BA' },
    { id: 'BW+267', code: '+267', name: 'Botswana', flag: 'BW' },
    { id: 'BR+55', code: '+55', name: 'Brazil', flag: 'BR' },
    { id: 'IO+246', code: '+246', name: 'British Indian Ocean Territory', flag: 'IO' },
    { id: 'BN+673', code: '+673', name: 'Brunei', flag: 'BN' },
    { id: 'BG+359', code: '+359', name: 'Bulgaria', flag: 'BG' },
    { id: 'BF+226', code: '+226', name: 'Burkina Faso', flag: 'BF' },
    { id: 'BI+257', code: '+257', name: 'Burundi', flag: 'BI' },
    { id: 'KH+855', code: '+855', name: 'Cambodia', flag: 'KH' },
    { id: 'CM+237', code: '+237', name: 'Cameroon', flag: 'CM' },
    { id: 'CA+1', code: '+1', name: 'Canada', flag: 'CA' },
    { id: 'CV+238', code: '+238', name: 'Cape Verde', flag: 'CV' },
    { id: 'BQ+599', code: '+599', name: 'Caribbean Netherlands', flag: 'BQ' },
    { id: 'CF+236', code: '+236', name: 'Central African Republic', flag: 'CF' },
    { id: 'TD+235', code: '+235', name: 'Chad', flag: 'TD' },
    { id: 'CL+56', code: '+56', name: 'Chile', flag: 'CL' },
    { id: 'CN+86', code: '+86', name: 'China', flag: 'CN' },
    { id: 'CO+57', code: '+57', name: 'Colombia', flag: 'CO' },
    { id: 'KM+269', code: '+269', name: 'Comoros', flag: 'KM' },
    { id: 'CD+243', code: '+243', name: 'Congo', flag: 'CD' },
    { id: 'CR+506', code: '+506', name: 'Costa Rica', flag: 'CR' },
    { id: 'CI+225', code: '+225', name: 'Côte d’Ivoire', flag: 'CI' },
    { id: 'HR+385', code: '+385', name: 'Croatia', flag: 'HR' },
    { id: 'CU+53', code: '+53', name: 'Cuba', flag: 'CU' },
    { id: 'CW+599', code: '+599', name: 'Curaçao', flag: 'CW' },
    { id: 'CY+357', code: '+357', name: 'Cyprus', flag: 'CY' },
    { id: 'CZ+420', code: '+420', name: 'Czech Republic', flag: 'CZ' },
    { id: 'DK+45', code: '+45', name: 'Denmark', flag: 'DK' },
    { id: 'DJ+253', code: '+253', name: 'Djibouti', flag: 'DJ' },
    { id: 'DM+1767', code: '+1767', name: 'Dominica', flag: 'DM' },
    { id: 'DO+1', code: '+1', name: 'Dominican Republic', flag: 'DO' },
    { id: 'EC+593', code: '+593', name: 'Ecuador', flag: 'EC' },
    { id: 'EG+20', code: '+20', name: 'Egypt', flag: 'EG' },
    { id: 'SV+503', code: '+503', name: 'El Salvador', flag: 'SV' },
    { id: 'GQ+240', code: '+240', name: 'Equatorial Guinea', flag: 'GQ' },
    { id: 'ER+291', code: '+291', name: 'Eritrea', flag: 'ER' },
    { id: 'EE+372', code: '+372', name: 'Estonia', flag: 'EE' },
    { id: 'ET+251', code: '+251', name: 'Ethiopia', flag: 'ET' },
    { id: 'FJ+679', code: '+679', name: 'Fiji', flag: 'FJ' },
    { id: 'FI+358', code: '+358', name: 'Finland', flag: 'FI' },
    { id: 'FR+33', code: '+33', name: 'France', flag: 'FR' },
    { id: 'GF+594', code: '+594', name: 'French Guiana', flag: 'GF' },
    { id: 'PF+689', code: '+689', name: 'French Polynesia', flag: 'PF' },
    { id: 'GA+241', code: '+241', name: 'Gabon', flag: 'GA' },
    { id: 'GM+220', code: '+220', name: 'Gambia', flag: 'GM' },
    { id: 'GE+995', code: '+995', name: 'Georgia', flag: 'GE' },
    { id: 'DE+49', code: '+49', name: 'Germany', flag: 'DE' },
    { id: 'GH+233', code: '+233', name: 'Ghana', flag: 'GH' },
    { id: 'GR+30', code: '+30', name: 'Greece', flag: 'GR' },
    { id: 'GD+1473', code: '+1473', name: 'Grenada', flag: 'GD' },
    { id: 'GP+590', code: '+590', name: 'Guadeloupe', flag: 'GP' },
    { id: 'GU+1671', code: '+1671', name: 'Guam', flag: 'GU' },
    { id: 'GT+502', code: '+502', name: 'Guatemala', flag: 'GT' },
    { id: 'GN+224', code: '+224', name: 'Guinea', flag: 'GN' },
    { id: 'GW+245', code: '+245', name: 'Guinea-Bissau', flag: 'GW' },
    { id: 'GY+592', code: '+592', name: 'Guyana', flag: 'GY' },
    { id: 'HT+509', code: '+509', name: 'Haiti', flag: 'HT' },
    { id: 'HN+504', code: '+504', name: 'Honduras', flag: 'HN' },
    { id: 'HK+852', code: '+852', name: 'Hong Kong', flag: 'HK' },
    { id: 'HU+36', code: '+36', name: 'Hungary', flag: 'HU' },
    { id: 'IS+354', code: '+354', name: 'Iceland', flag: 'IS' },
    { id: 'IN+91', code: '+91', name: 'India', flag: 'IN' },
    { id: 'ID+62', code: '+62', name: 'Indonesia', flag: 'ID' },
    { id: 'IR+98', code: '+98', name: 'Iran', flag: 'IR' },
    { id: 'IQ+964', code: '+964', name: 'Iraq', flag: 'IQ' },
    { id: 'IE+353', code: '+353', name: 'Ireland', flag: 'IE' },
    { id: 'IL+972', code: '+972', name: 'Israel', flag: 'IL' },
    { id: 'IT+39', code: '+39', name: 'Italy', flag: 'IT' },
    { id: 'JM+1876', code: '+1876', name: 'Jamaica', flag: 'JM' },
    { id: 'JP+81', code: '+81', name: 'Japan', flag: 'JP' },
    { id: 'JO+962', code: '+962', name: 'Jordan', flag: 'JO' },
    { id: 'KZ+7', code: '+7', name: 'Kazakhstan', flag: 'KZ' },
    { id: 'KE+254', code: '+254', name: 'Kenya', flag: 'KE' },
    { id: 'KI+686', code: '+686', name: 'Kiribati', flag: 'KI' },
    { id: 'KP+850', code: '+850', name: 'North Korea', flag: 'KP' },
    { id: 'KR+82', code: '+82', name: 'South Korea', flag: 'KR' },
    { id: 'KW+965', code: '+965', name: 'Kuwait', flag: 'KW' },
    { id: 'KG+996', code: '+996', name: 'Kyrgyzstan', flag: 'KG' },
    { id: 'LA+856', code: '+856', name: 'Laos', flag: 'LA' },
    { id: 'LV+371', code: '+371', name: 'Latvia', flag: 'LV' },
    { id: 'LB+961', code: '+961', name: 'Lebanon', flag: 'LB' },
    { id: 'LS+266', code: '+266', name: 'Lesotho', flag: 'LS' },
    { id: 'LR+231', code: '+231', name: 'Liberia', flag: 'LR' },
    { id: 'LY+218', code: '+218', name: 'Libya', flag: 'LY' },
    { id: 'LI+423', code: '+423', name: 'Liechtenstein', flag: 'LI' },
    { id: 'LT+370', code: '+370', name: 'Lithuania', flag: 'LT' },
    { id: 'LU+352', code: '+352', name: 'Luxembourg', flag: 'LU' },
    { id: 'MO+853', code: '+853', name: 'Macau', flag: 'MO' },
    { id: 'MK+389', code: '+389', name: 'North Macedonia', flag: 'MK' },
    { id: 'MG+261', code: '+261', name: 'Madagascar', flag: 'MG' },
    { id: 'MW+265', code: '+265', name: 'Malawi', flag: 'MW' },
    { id: 'MY+60', code: '+60', name: 'Malaysia', flag: 'MY' },
    { id: 'MV+960', code: '+960', name: 'Maldives', flag: 'MV' },
    { id: 'ML+223', code: '+223', name: 'Mali', flag: 'ML' },
    { id: 'MT+356', code: '+356', name: 'Malta', flag: 'MT' },
    { id: 'MH+692', code: '+692', name: 'Marshall Islands', flag: 'MH' },
    { id: 'MQ+596', code: '+596', name: 'Martinique', flag: 'MQ' },
    { id: 'MR+222', code: '+222', name: 'Mauritania', flag: 'MR' },
    { id: 'MU+230', code: '+230', name: 'Mauritius', flag: 'MU' },
    { id: 'YT+262', code: '+262', name: 'Mayotte', flag: 'YT' },
    { id: 'MX+52', code: '+52', name: 'Mexico', flag: 'MX' },
    { id: 'FM+691', code: '+691', name: 'Micronesia', flag: 'FM' },
    { id: 'MD+373', code: '+373', name: 'Moldova', flag: 'MD' },
    { id: 'MC+377', code: '+377', name: 'Monaco', flag: 'MC' },
    { id: 'MN+976', code: '+976', name: 'Mongolia', flag: 'MN' },
    { id: 'ME+382', code: '+382', name: 'Montenegro', flag: 'ME' },
    { id: 'MS+1664', code: '+1664', name: 'Montserrat', flag: 'MS' },
    { id: 'MA+212', code: '+212', name: 'Morocco', flag: 'MA' },
    { id: 'MZ+258', code: '+258', name: 'Mozambique', flag: 'MZ' },
    { id: 'MM+95', code: '+95', name: 'Myanmar', flag: 'MM' },
    { id: 'NA+264', code: '+264', name: 'Namibia', flag: 'NA' },
    { id: 'NR+674', code: '+674', name: 'Nauru', flag: 'NR' },
    { id: 'NP+977', code: '+977', name: 'Nepal', flag: 'NP' },
    { id: 'NL+31', code: '+31', name: 'Netherlands', flag: 'NL' },
    { id: 'NC+687', code: '+687', name: 'New Caledonia', flag: 'NC' },
    { id: 'NZ+64', code: '+64', name: 'New Zealand', flag: 'NZ' },
    { id: 'NI+505', code: '+505', name: 'Nicaragua', flag: 'NI' },
    { id: 'NE+227', code: '+227', name: 'Niger', flag: 'NE' },
    { id: 'NG+234', code: '+234', name: 'Nigeria', flag: 'NG' },
    { id: 'MP+1670', code: '+1670', name: 'Northern Mariana Islands', flag: 'MP' },
    { id: 'NO+47', code: '+47', name: 'Norway', flag: 'NO' },
    { id: 'OM+968', code: '+968', name: 'Oman', flag: 'OM' },
    { id: 'PK+92', code: '+92', name: 'Pakistan', flag: 'PK' },
    { id: 'PW+680', code: '+680', name: 'Palau', flag: 'PW' },
    { id: 'PS+970', code: '+970', name: 'Palestine', flag: 'PS' },
    { id: 'PA+507', code: '+507', name: 'Panama', flag: 'PA' },
    { id: 'PG+675', code: '+675', name: 'Papua New Guinea', flag: 'PG' },
    { id: 'PY+595', code: '+595', name: 'Paraguay', flag: 'PY' },
    { id: 'PE+51', code: '+51', name: 'Peru', flag: 'PE' },
    { id: 'PH+63', code: '+63', name: 'Philippines', flag: 'PH' },
    { id: 'PL+48', code: '+48', name: 'Poland', flag: 'PL' },
    { id: 'PT+351', code: '+351', name: 'Portugal', flag: 'PT' },
    { id: 'PR+1939', code: '+1939', name: 'Puerto Rico', flag: 'PR' },
    { id: 'QA+974', code: '+974', name: 'Qatar', flag: 'QA' },
    { id: 'CG+242', code: '+242', name: 'Republic of the Congo', flag: 'CG' },
    { id: 'RE+262', code: '+262', name: 'Réunion', flag: 'RE' },
    { id: 'RO+40', code: '+40', name: 'Romania', flag: 'RO' },
    { id: 'RU+7', code: '+7', name: 'Russia', flag: 'RU' },
    { id: 'RW+250', code: '+250', name: 'Rwanda', flag: 'RW' },
    { id: 'BL+590', code: '+590', name: 'Saint Barthélemy', flag: 'BL' },
    { id: 'SH+290', code: '+290', name: 'Saint Helena', flag: 'SH' },
    { id: 'KN+1869', code: '+1869', name: 'Saint Kitts and Nevis', flag: 'KN' },
    { id: 'LC+1758', code: '+1758', name: 'Saint Lucia', flag: 'LC' },
    { id: 'MF+590', code: '+590', name: 'Saint Martin', flag: 'MF' },
    { id: 'PM+508', code: '+508', name: 'Saint Pierre and Miquelon', flag: 'PM' },
    { id: 'VC+1784', code: '+1784', name: 'Saint Vincent and the Grenadines', flag: 'VC' },
    { id: 'WS+685', code: '+685', name: 'Samoa', flag: 'WS' },
    { id: 'SM+378', code: '+378', name: 'San Marino', flag: 'SM' },
    { id: 'ST+239', code: '+239', name: 'Sao Tome and Principe', flag: 'ST' },
    { id: 'SA+966', code: '+966', name: 'Saudi Arabia', flag: 'SA' },
    { id: 'SN+221', code: '+221', name: 'Senegal', flag: 'SN' },
    { id: 'RS+381', code: '+381', name: 'Serbia', flag: 'RS' },
    { id: 'SC+248', code: '+248', name: 'Seychelles', flag: 'SC' },
    { id: 'SL+232', code: '+232', name: 'Sierra Leone', flag: 'SL' },
    { id: 'SG+65', code: '+65', name: 'Singapore', flag: 'SG' },
    { id: 'SX+1721', code: '+1721', name: 'Sint Maarten', flag: 'SX' },
    { id: 'SK+421', code: '+421', name: 'Slovakia', flag: 'SK' },
    { id: 'SI+386', code: '+386', name: 'Slovenia', flag: 'SI' },
    { id: 'SB+677', code: '+677', name: 'Solomon Islands', flag: 'SB' },
    { id: 'SO+252', code: '+252', name: 'Somalia', flag: 'SO' },
    { id: 'ZA+27', code: '+27', name: 'South Africa', flag: 'ZA' },
    { id: 'SS+211', code: '+211', name: 'South Sudan', flag: 'SS' },
    { id: 'ES+34', code: '+34', name: 'Spain', flag: 'ES' },
    { id: 'LK+94', code: '+94', name: 'Sri Lanka', flag: 'LK' },
    { id: 'SD+249', code: '+249', name: 'Sudan', flag: 'SD' },
    { id: 'SR+597', code: '+597', name: 'Suriname', flag: 'SR' },
    { id: 'SJ+47', code: '+47', name: 'Svalbard and Jan Mayen', flag: 'SJ' },
    { id: 'SZ+268', code: '+268', name: 'Swaziland', flag: 'SZ' },
    { id: 'SE+46', code: '+46', name: 'Sweden', flag: 'SE' },
    { id: 'CH+41', code: '+41', name: 'Switzerland', flag: 'CH' },
    { id: 'SY+963', code: '+963', name: 'Syria', flag: 'SY' },
    { id: 'TW+886', code: '+886', name: 'Taiwan', flag: 'TW' },
    { id: 'TJ+992', code: '+992', name: 'Tajikistan', flag: 'TJ' },
    { id: 'TZ+255', code: '+255', name: 'Tanzania', flag: 'TZ' },
    { id: 'TH+66', code: '+66', name: 'Thailand', flag: 'TH' },
    { id: 'TG+228', code: '+228', name: 'Togo', flag: 'TG' },
    { id: 'TK+690', code: '+690', name: 'Tokelau', flag: 'TK' },
    { id: 'TO+676', code: '+676', name: 'Tonga', flag: 'TO' },
    { id: 'TT+1868', code: '+1868', name: 'Trinidad and Tobago', flag: 'TT' },
    { id: 'TN+216', code: '+216', name: 'Tunisia', flag: 'TN' },
    { id: 'TR+90', code: '+90', name: 'Turkey', flag: 'TR' },
    { id: 'TM+993', code: '+993', name: 'Turkmenistan', flag: 'TM' },
    { id: 'TV+688', code: '+688', name: 'Tuvalu', flag: 'TV' },
    { id: 'UG+256', code: '+256', name: 'Uganda', flag: 'UG' },
    { id: 'UA+380', code: '+380', name: 'Ukraine', flag: 'UA' },
    { id: 'AE+971', code: '+971', name: 'United Arab Emirates', flag: 'AE' },
    { id: 'GB+44', code: '+44', name: 'United Kingdom', flag: 'GB' },
    { id: 'US+1', code: '+1', name: 'United States', flag: 'US' },
    { id: 'UY+598', code: '+598', name: 'Uruguay', flag: 'UY' },
    { id: 'UZ+998', code: '+998', name: 'Uzbekistan', flag: 'UZ' },
    { id: 'VU+678', code: '+678', name: 'Vanuatu', flag: 'VU' },
    { id: 'VA+379', code: '+379', name: 'Vatican', flag: 'VA' },
    { id: 'VE+58', code: '+58', name: 'Venezuela', flag: 'VE' },
    { id: 'VN+84', code: '+84', name: 'Vietnam', flag: 'VN' },
    { id: 'WF+681', code: '+681', name: 'Wallis and Futuna', flag: 'WF' },
    { id: 'EH+212', code: '+212', name: 'Western Sahara', flag: 'EH' },
    { id: 'YE+967', code: '+967', name: 'Yemen', flag: 'YE' },
    { id: 'ZM+260', code: '+260', name: 'Zambia', flag: 'ZM' },
    { id: 'ZW+263', code: '+263', name: 'Zimbabwe', flag: 'ZW' },
] as const;  
