export interface UserData {
  name: string;
  user_name: string;
}
// Generated by https://quicktype.io

export interface User {
  uid: string;
  email: string;
  emailVerified: boolean;
  displayName: string;
  isAdmin: boolean;
}
